Add Type to bill.Charge
invopop/gobl pull request #127
Opened 2023-04-06 16:11 UTC by lucanioi

- Add a new field `Type` to Charges
- For certain types of Charges that are distinguished from others at the regime-level. In the case of Italy, there is `Bollo`, or duty stamps, which is to be included in a special field. 

--
**Notes**
- I was going to create a `ChargeTypeDef` in the `bill` package, but it since the `bill` package depends on `tax` I was not able to utilise ChargeTypeDef in `tax.Regime`. Went with reutilising `tax.KeyDefinition` instead.

2023-04-06 17:28 UTC, samlown reviewed
I think there needs to be some changes around key/type usage, so that they are more consistent.

2023-04-06 17:28 UTC, samlown commented on regimes/it/charges.go
> +	ChargeTypeBollo cbc.Key = "bollo"
It might be worth having the variable names in English.

```suggestion
	ChargeKeyStampDuty cbc.Key = "stamp-duty"
```

2023-04-06 17:28 UTC, samlown commented on tax/regime.go
> +	ChargeTypes []*KeyDefinition `json:"charge_types,omitempty" jsonschema:"title=Charge Types"`
Also probably wants to be `ChargeKeys` instead of Types.

2023-04-14 14:33 UTC, samlown requested changes

2023-04-14 14:33 UTC, samlown commented on regimes/it/charges.go
> +			i18n.EN: "Stamp Stamp",
Typo!
```suggestion
			i18n.EN: "Stamp Duty",
```

2023-04-14 14:33 UTC, samlown commented on regimes/it/charges.go
> +			i18n.IT: "Bollo",
Should the name be "tassa di bollo"?

```suggestion
			i18n.IT: "Tassa di Bollo",
```

2023-04-17 13:08 UTC, lucanioi commented on regimes/it/charges.go
> +			i18n.EN: "Stamp Stamp",
yikes. fixed!

2023-04-23 15:17 UTC, samlown approved these changes
LGTM. Just a quick suggestion there.

2023-04-23 15:17 UTC, samlown commented on bill/charges.go
> +	// Type of the charge, useful when regimes require special types of charges.
```suggestion
	// Key for grouping or identifying charges for tax purposes.
```

2023-04-24 15:50 UTC, merged