X-Rechnung Add-on
invopop/gobl pull request #393
Opened 2024-10-15 15:49 UTC by apardods

Validation rules implemented that could be considered too strict:
- Field Buyer Reference (Ordering.Code in GOBL) is mandatory
- Field Payment Instructions is mandatory
- Seller Contact Point (Person.Name in GOBL), Email and Phone Number are mandatory

Other key rules:
- City and post code mandatory for all addresses (Seller and Buyer/DeliverTo, if provided)
- If SEPA Credit Transfer, IBAN is mandatory
- If Direct Debit, Mandate Reference, Creditor Identifier and Debited Account Identifier are mandatory
- VAT percentage is mandatory (but added on calculate)

2024-10-18 08:14 UTC, samlown requested changes
Its going in the right direction, but lot's of changes required. Please do closely look at the other example addons to make sure everything is as similar as possible. Take special note of the usage of `validation.Skip` for example also, this is important.

2024-10-18 08:14 UTC, samlown commented on addons/de/xrechnung/extensions.go
> +var ExtKeyTaxRate cbc.Key = "de-xrechnung-tax-rate"
Is "tax rate" the correct name? The definitions also cover tax categories. I'd strongly suggest adding a comment with the link to the source information to be able to double check.

2024-10-18 08:14 UTC, samlown commented on addons/de/xrechnung/instructions.go
> +}
Please check the other regime and addon implementations. It is important that the base GOBL types are maintained and only extended if needed with the `+` stuff.

2024-10-18 08:14 UTC, samlown commented on addons/de/xrechnung/instructions.go
> +func ValidatePaymentInstructions(value interface{}) error {
I'd keep these methods private, i.e. lower-case `v` at the start.

2024-10-18 08:14 UTC, samlown commented on addons/de/xrechnung/instructions.go
> +	if !ok || inv == nil || inv.Payment == nil || inv.Payment.Instructions == nil {
This doesn't look right. I'd expect the `ValidatePaymentInstructions` method to only validate a `pay.Instructions` instance.

2024-10-18 08:14 UTC, samlown commented on addons/de/xrechnung/instructions.go
> +			validation.By(validatePaymentKey),
missing `validation.Skip` under here (there are lots of other cases also)

2024-10-18 08:14 UTC, samlown commented on addons/de/xrechnung/instructions.go
> +		return validation.NewError("type", "Invalid payment key")
I'm not sure about this usage of `NewError`, what is "`type`"? Also, convention is that error messages should not start with capital letters.

2024-10-18 08:14 UTC, samlown commented on addons/de/xrechnung/instructions.go
> +			validation.Required.Error("Mandate reference is mandatory for direct debit"),
Are these messages necessary?

2024-10-18 08:14 UTC, samlown commented on addons/de/xrechnung/instructions_test.go
> +		assert.NoError(t, xrechnung.ValidatePaymentInstructions(inv))
I'd run the validation on the whole Invoice to make sure nothin else is broken. Please see the other examples.

2024-10-18 08:14 UTC, samlown commented on addons/de/xrechnung/invoices.go
> +}
Rather than modify the invoice types (which is strictly prohibited), checkout the usage of "tags" and "scenarios" in other addons.

2024-10-25 11:30 UTC, cavalle approved these changes
Beautiful! Totally feels like the right way to separate the extensions, scenarios, validations and normalisations derived from EN16931 from those derived from each specific CIUS/Extension.

2024-10-31 14:58 UTC, merged